# Generated by Django 5.1.7 on 2025-06-25 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_cart_wishlist'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='image',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
